/**
 * Generates extensions/<name>/scripts/install.ts from scripts/adapters.json.
 *
 *   bun run scripts/generate-install-scripts.ts           # write
 *   bun run scripts/generate-install-scripts.ts --check    # verify, exit 1 on drift
 *
 * The generated scripts stay committed so each extension remains self-contained
 * and independently installable - the generator is a build-time authoring aid,
 * not a runtime dependency.
 */
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const configPath = join(root, "scripts", "adapters.json");

interface NpmPackage {
  name: string;
  version: string;
}

interface NpmAdapter {
  kind: "npm";
  binName: string;
  binTarget: string;
  trust?: boolean;
  packages: NpmPackage[];
}

interface GithubReleaseAdapter {
  kind: "github-release";
  binName: string;
  /** Human-readable name used in log output. Defaults to binName. */
  displayName?: string;
  repo: string;
  tag: string;
  unsupportedPlatforms?: Record<string, string>;
}

type Adapter = NpmAdapter | GithubReleaseAdapter;

const banner = (extName: string, pinnedAt: string) =>
  `// Code generated by scripts/generate-install-scripts.ts. DO NOT EDIT.\n` +
  `// Source of truth: scripts/adapters.json -> adapters["${extName}"]\n` +
  `// Version pins captured ${pinnedAt}. To change a pin, edit adapters.json and regenerate.\n\n`;

/** Registry fallback chain - preserved verbatim from the original hand-written scripts. */
const REGISTRIES = `const registries: { name: string; url: string }[] = [
  { name: "npm 官方源", url: "https://registry.npmjs.org" },
  { name: "华为开源镜像站", url: "https://repo.huaweicloud.com/repository/npm/" },
  { name: "腾讯云镜像源", url: "https://mirrors.cloud.tencent.com/npm/" },
  { name: "淘宝镜像源", url: "https://registry.npmmirror.com" },
];`;

function renderNpm(a: NpmAdapter): string {
  const specs = a.packages.map((p) => `${p.name}@${p.version}`);
  const trust = a.trust ? "--trust " : "";

  // Reproduce the two shapes already present in the repo: a bare PKG constant for
  // single-package adapters, an indexed PKGS array for the two-package ones.
  const single = specs.length === 1;
  const decl = single
    ? `const PKG = ${JSON.stringify(specs[0])};`
    : `const PKGS = [${specs.map((s) => JSON.stringify(s)).join(", ")}];`;
  const args = single ? "\${PKG}" : specs.map((_, i) => `\${PKGS[${i}]}`).join(" ");

  return `import { $ } from "bun";
import { mkdirSync, symlinkSync, existsSync } from "fs";
import { join } from "path";

const dir = process.env.AIONUI_AGENT_INSTALL_DIR;
if (!dir) {
  console.error("[install] AIONUI_AGENT_INSTALL_DIR is not set");
  process.exit(1);
}

${decl}

${REGISTRIES}

let installed = false;

for (const reg of registries) {
  console.log(\`[install] 尝试 \${reg.name} (\${reg.url}) ...\`);
  try {
    await $\`bun install --cwd \${dir} ${trust}${args} --registry=\${reg.url}\`.quiet();
    console.log(\`[install] 通过 \${reg.name} 安装成功\`);
    installed = true;
    break;
  } catch {
    console.warn(\`[install] \${reg.name} 安装失败，尝试下一个源...\`);
  }
}

if (!installed) {
  console.error("[install] 所有源均安装失败，请检查网络连接后重试");
  process.exit(1);
}

const binDir = join(dir, "bin");
mkdirSync(binDir, { recursive: true });
const link = join(binDir, ${JSON.stringify(a.binName)});
if (!existsSync(link)) {
  symlinkSync(join(dir, "node_modules", ".bin", ${JSON.stringify(a.binTarget)}), link);
}
`;
}

function renderGithubRelease(a: GithubReleaseAdapter): string {
  const label = a.displayName ?? a.binName;
  const guards = Object.entries(a.unsupportedPlatforms ?? {})
    .map(
      ([platform, message]) =>
        `if (process.platform === ${JSON.stringify(platform)}) {\n  throw new Error(${JSON.stringify(message)});\n}\n\n`,
    )
    .join("");

  return `import { $ } from "bun";

${guards}const dir = process.env.AIONUI_AGENT_INSTALL_DIR;
if (!dir) {
  console.error("[install] AIONUI_AGENT_INSTALL_DIR is not set");
  process.exit(1);
}

const TAG = ${JSON.stringify(a.tag)};
const arch = process.arch === "arm64" ? "arm64" : "x86_64";
const platform = process.platform === "darwin" ? "darwin" : "linux";
const binaryUrl = \`https://github.com/${a.repo}/releases/download/\${TAG}/${a.binName}-\${platform}-\${arch}\`;
const binDir = \`\${dir}/bin\`;
const binaryPath = \`\${binDir}/${a.binName}\`;

console.log(\`[install] Downloading ${a.binName} from \${binaryUrl} ...\`);
try {
  await $\`mkdir -p \${binDir}\`;
  await $\`curl -fsSL \${binaryUrl} -o \${binaryPath}\`;
  await $\`chmod +x \${binaryPath}\`;
  console.log(\`[install] ${label} installed to \${binaryPath}\`);
} catch {
  console.error("[install] Failed to download ${a.binName} binary");
  process.exit(1);
}
`;
}

function render(extName: string, adapter: Adapter, pinnedAt: string): string {
  const body =
    adapter.kind === "npm"
      ? renderNpm(adapter)
      : adapter.kind === "github-release"
        ? renderGithubRelease(adapter)
        : null;

  if (body === null) {
    throw new Error(`${extName}: unknown install kind "${(adapter as { kind: string }).kind}"`);
  }
  return banner(extName, pinnedAt) + body;
}

const check = process.argv.includes("--check");
const config = JSON.parse(readFileSync(configPath, "utf8")) as {
  pinnedAt: string;
  adapters: Record<string, Adapter>;
};

let drifted = 0;
let written = 0;

for (const [extName, adapter] of Object.entries(config.adapters)) {
  const target = join(root, "extensions", extName, "scripts", "install.ts");
  if (!existsSync(dirname(target))) {
    console.error(`✗ ${extName}: extensions/${extName}/scripts/ does not exist`);
    drifted++;
    continue;
  }

  const expected = render(extName, adapter, config.pinnedAt);
  const actual = existsSync(target) ? readFileSync(target, "utf8") : null;

  if (actual === expected) {
    console.log(`  ${extName}: up to date`);
    continue;
  }

  if (check) {
    console.error(`✗ ${extName}: install.ts differs from generated output`);
    drifted++;
  } else {
    writeFileSync(target, expected);
    console.log(`✓ ${extName}: written`);
    written++;
  }
}

// Anything in extensions/ without a config entry would silently keep a
// hand-written script - surface it rather than let it drift unnoticed.
const { readdirSync } = await import("fs");
const onDisk = readdirSync(join(root, "extensions")).filter((d) => d.startsWith("aionext-"));
const unmanaged = onDisk.filter((d) => !(d in config.adapters));
if (unmanaged.length > 0) {
  console.warn(`! not managed by adapters.json: ${unmanaged.join(", ")}`);
}

if (check && drifted > 0) {
  console.error(`\n${drifted} script(s) out of sync. Run: bun run scripts/generate-install-scripts.ts`);
  process.exit(1);
}

if (!check) {
  console.log(`\n${written} written, ${onDisk.length - unmanaged.length} managed.`);
}
