// Code generated by scripts/generate-install-scripts.ts. DO NOT EDIT.
// Source of truth: scripts/adapters.json -> adapters["aionext-goose"]
// Version pins captured 2026-07-26. To change a pin, edit adapters.json and regenerate.

import { $ } from "bun";

if (process.platform === "win32") {
  throw new Error("Goose does not support Windows. Please visit https://github.com/block/goose for manual installation.");
}

const dir = process.env.AIONUI_AGENT_INSTALL_DIR;
if (!dir) {
  console.error("[install] AIONUI_AGENT_INSTALL_DIR is not set");
  process.exit(1);
}

const TAG = "v1.44.0";
const arch = process.arch === "arm64" ? "arm64" : "x86_64";
const platform = process.platform === "darwin" ? "darwin" : "linux";
const binaryUrl = `https://github.com/block/goose/releases/download/${TAG}/goose-${platform}-${arch}`;
const binDir = `${dir}/bin`;
const binaryPath = `${binDir}/goose`;

console.log(`[install] Downloading goose from ${binaryUrl} ...`);
try {
  await $`mkdir -p ${binDir}`;
  await $`curl -fsSL ${binaryUrl} -o ${binaryPath}`;
  await $`chmod +x ${binaryPath}`;
  console.log(`[install] Goose installed to ${binaryPath}`);
} catch {
  console.error("[install] Failed to download goose binary");
  process.exit(1);
}
